# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 23:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('cedula', models.PositiveIntegerField(verbose_name='Cedula')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('certificadoImpreso', models.BooleanField(verbose_name='Certificado')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Evento')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('lugar', models.CharField(max_length=60, verbose_name='Lugar')),
                ('tipo', models.CharField(choices=[('PO', 'Ponencia'), ('RE', 'Recreativo'), ('GO', 'Global'), ('CO', 'Convesatorio'), ('OT', 'Otro')], max_length=15, verbose_name='Tipo')),
            ],
            options={
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('cedula', models.IntegerField(verbose_name='Cedula o Rif')),
                ('gerente', models.CharField(max_length=50, verbose_name='Encargado')),
                ('sitioWeb', models.URLField(verbose_name='Sitio Web')),
                ('direccion', models.TextField(max_length=150, verbose_name='Direccion')),
                ('telefono', models.PositiveIntegerField(verbose_name='Telefono')),
                ('modalidad', models.CharField(choices=[('MO', 'Monetario'), ('AP', 'Apoyo'), ('PU', 'Publicidad'), ('PA', 'Participante'), ('OR', 'Organizativo')], max_length=15, verbose_name='Modalidad de Patrocinio')),
                ('eventos', models.ManyToManyField(to='registro.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Ponencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Ponencia')),
                ('descripcion', models.TextField(max_length=200, verbose_name='Descripcion')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Ponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre Completo')),
                ('cedula', models.PositiveIntegerField(verbose_name='Cedula')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('telefono', models.PositiveIntegerField(verbose_name='Telefono')),
                ('website', models.URLField(verbose_name='Sitio Web')),
                ('eventos', models.ManyToManyField(to='registro.Evento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ponencia',
            name='ponente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Ponente'),
        ),
        migrations.AddField(
            model_name='asistente',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Evento'),
        ),
    ]
