# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_remove_ponente_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponente',
            name='eventos',
            field=models.ManyToManyField(blank=True, to='registro.Evento'),
        ),
        migrations.AlterField(
            model_name='ponente',
            name='telefono',
            field=models.PositiveIntegerField(blank=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='ponente',
            name='website',
            field=models.URLField(blank=True, verbose_name='Sitio Web'),
        ),
    ]
