# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20160229_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistente',
            name='id',
        ),
        migrations.AlterField(
            model_name='asistente',
            name='cedula',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Cedula'),
        ),
    ]
