# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20160301_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='evento',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Evento'),
        ),
    ]
