# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20160301_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistente',
            name='certificadoImpreso',
        ),
    ]
